import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.CIVIL_CONFIG||{};
const registrationForm=document.querySelector('#registrationForm'),proofForm=document.querySelector('#proofForm'),lookupForm=document.querySelector('#lookupForm');
const registrationMessage=document.querySelector('#registrationMessage'),proofMessage=document.querySelector('#proofMessage'),lookupResult=document.querySelector('#lookupResult');
const amountLabel=document.querySelector('#amountLabel'),amountHint=document.querySelector('#amountHint'),formAmount=document.querySelector('#formAmount'),upiText=document.querySelector('#upiText'),qrPlaceholder=document.querySelector('#qrPlaceholder');
const eventDate=document.querySelector('#eventDate'),eventDateBottom=document.querySelector('#eventDateBottom'),eventVenue=document.querySelector('#eventVenue'),eventVenueBottom=document.querySelector('#eventVenueBottom'),eventSupport=document.querySelector('#eventSupport');
const juniorContribution=700, seniorContribution=1400;
const configured=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey); const supabase=configured?createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
function setMessage(el,text,error=false){el.textContent=text;el.style.color=error?'#ff9c9c':''}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setAmount(value){const text=value?`₹${Number(value).toLocaleString('en-IN')}`:'JR ₹700 · SR ₹1,400';if(amountLabel)amountLabel.textContent=text;if(formAmount)formAmount.textContent=text;if(amountHint)amountHint.textContent=value?'Selected contribution amount.':'Junior ₹700 · Senior ₹1,400'}
function contributionForYear(year){return year==='1st Year'?juniorContribution:seniorContribution;}
function refreshContributionFromYear(){const year=registrationForm?.querySelector('[name="year"]')?.value;const value=year?contributionForYear(year):0;if(formAmount)formAmount.textContent=year?`₹${value.toLocaleString('en-IN')}`:'Select year';}
function setEventDetails(date,venue,support){if(eventDate)eventDate.textContent=date||'To be announced';if(eventDateBottom)eventDateBottom.textContent=date||'To be announced';if(eventVenue)eventVenue.textContent=venue||'SMVDU Campus';if(eventVenueBottom)eventVenueBottom.textContent=venue||'SMVDU Campus';if(eventSupport)eventSupport.textContent=support||'Contact Civil organizers'}
function renderQR(){
  const accounts=Array.isArray(cfg.upiIds)?cfg.upiIds:[];
  if(!accounts.length){qrPlaceholder.textContent='Civil UPI is not configured yet.';upiText.textContent='UPI accounts: not configured';return}
  const amount=Number(cfg.contribution||0);
  qrPlaceholder.innerHTML=accounts.map((account,index)=>{
    const uri=`upi://pay?pa=${encodeURIComponent(account.id)}&pn=${encodeURIComponent(account.name||'Civil Engineering Freshers 26')}${amount?`&am=${amount.toFixed(2)}`:''}&cu=INR`;
    const qr=`https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=8&data=${encodeURIComponent(uri)}`;
    return `<div class="upi-card"><img class="qr-image" alt="UPI QR ${index+1}" src="${qr}"><div><strong>${escapeHtml(account.name||'Civil organizer')}</strong><br><span>${escapeHtml(account.id)}</span></div></div>`;
  }).join('');
  upiText.textContent=`${accounts.length} Civil UPI account${accounts.length>1?'s':''} available for payment.`;
}
setAmount(0);setEventDetails(cfg.eventDate,cfg.venue||'Sanjeevni Resort',cfg.supportText);renderQR();
registrationForm?.querySelector('[name="year"]')?.addEventListener('change',refreshContributionFromYear);
async function loadConfig(){if(!supabase)return;const{data,error}=await supabase.from('event_config').select('*').eq('id',true).maybeSingle();if(error||!data)return;if(data.contribution && Number(data.contribution)>0){cfg.contribution=data.contribution}if(data.upi_id){cfg.upiIds=[{id:data.upi_id,name:'Civil organizer'}];renderQR()}setEventDetails(data.event_date,data.venue||'Sanjeevni Resort',data.support_text)}
registrationForm.addEventListener('submit',async e=>{e.preventDefault();if(!supabase){setMessage(registrationMessage,'Civil Supabase is not connected yet. Configure config.js first.',true);return}const data=Object.fromEntries(new FormData(e.currentTarget));
const selectedContribution=contributionForYear(data.year);if(!/^\d{10}$/.test(data.phone)){setMessage(registrationMessage,'Enter a valid 10-digit phone number.',true);return}setMessage(registrationMessage,'Creating your Civil registration…');const{data:ref,error:refError}=await supabase.rpc('next_civil_reference');if(refError){setMessage(registrationMessage,refError.message,true);return}const{error}=await supabase.from('registrations').insert({...data,reference_id:ref,contribution:selectedContribution});if(error){setMessage(registrationMessage,error.message,true);return}setMessage(registrationMessage,`Registration successful. Your reference ID is ${ref}. Contribution: ₹${selectedContribution.toLocaleString('en-IN')}. Save it for payment proof and pass lookup.`);e.currentTarget.reset()});
proofForm.addEventListener('submit',async e=>{e.preventDefault();if(!supabase){setMessage(proofMessage,'Civil Supabase is not connected yet.',true);return}const f=new FormData(e.currentTarget),reference=String(f.get('reference_id')||'').trim().toUpperCase(),file=f.get('screenshot');if(!reference||!(file instanceof File)||!file.size){setMessage(proofMessage,'Enter your reference ID and choose a screenshot.',true);return}if(file.size>5*1024*1024){setMessage(proofMessage,'Screenshot must be 5 MB or smaller.',true);return}setMessage(proofMessage,'Uploading payment proof…');const{data:reg,error:regError}=await supabase.from('registrations').select('reference_id').eq('reference_id',reference).maybeSingle();if(regError||!reg){setMessage(proofMessage,'Reference ID not found. Check it and try again.',true);return}const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`${reference}/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabase.storage.from('civil-payment-proofs').upload(path,file,{contentType:file.type,upsert:false});if(uploadError){setMessage(proofMessage,uploadError.message,true);return}const{error:proofError}=await supabase.from('payment_proofs').insert({reference_id:reference,storage_path:path});if(proofError){setMessage(proofMessage,proofError.message,true);return}await supabase.from('registrations').update({payment_status:'submitted'}).eq('reference_id',reference);setMessage(proofMessage,'Payment proof submitted successfully. Wait for Civil organizer verification.');e.currentTarget.reset()});
lookupForm.addEventListener('submit',async e=>{e.preventDefault();if(!supabase){lookupResult.textContent='Civil Supabase is not connected yet.';return}const reference=String(new FormData(e.currentTarget).get('reference_id')||'').trim();lookupResult.textContent='Checking…';const{data,error}=await supabase.rpc('lookup_civil_pass',{p_reference_id:reference});if(error){lookupResult.textContent=error.message;return}if(!data?.length){lookupResult.textContent='No Civil registration found for that reference ID.';return}const r=data[0],status=r.payment_status,statusText=status==='verified'?'VERIFIED — PASS READY':status==='submitted'?'PAYMENT PROOF SUBMITTED — AWAITING VERIFICATION':status==='rejected'?'PAYMENT PROOF REJECTED — CONTACT ORGANIZERS':'REGISTRATION RECEIVED — PAYMENT PROOF PENDING';lookupResult.innerHTML=`<strong>${escapeHtml(r.reference_id)}</strong><br>${escapeHtml(r.full_name)}<br><span>${statusText}</span>`});
loadConfig();
